# Generated by Django 5.2.1 on 2025-05-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('draft', 'Draft')], default='draft', max_length=20),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
