# Generated by Django 5.2.1 on 2025-05-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_is_featured_remove_project_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
