# Generated by Django 5.2.1 on 2025-06-13 21:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_donation_options_alter_project_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='user',
            new_name='donor',
        ),
        migrations.RenameField(
            model_name='projectreport',
            old_name='details',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='projectreport',
            old_name='reason',
            new_name='report_type',
        ),
        migrations.RenameField(
            model_name='projectreport',
            old_name='user',
            new_name='reporter',
        ),
        migrations.AlterUniqueTogether(
            name='projectreport',
            unique_together={('reporter', 'project')},
        ),
    ]
