# Generated by Django 5.2.1 on 2025-06-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreport',
            name='report_type',
            field=models.CharField(choices=[('inappropriate_content', 'Inappropriate Content'), ('spam', 'Spam'), ('fraud', 'Fraud/Scam'), ('copyright', 'Copyright Violation'), ('harassment', 'Harassment'), ('other', 'Other')], max_length=50),
        ),
    ]
