# Generated by Django 5.2.1 on 2025-06-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_commentreport_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_hidden_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderation_status',
            field=models.CharField(choices=[('active', 'Active'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected/Hidden')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='admin_action',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Report Approved'), ('dismissed', 'Report Dismissed')], default='pending', max_length=20),
        ),
    ]
