# Generated by Django 5.2.1 on 2025-06-11 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_options_alter_commentreport_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_active',
        ),
    ]
